name: build snp-qemu
on:
  push:
    branches:
    - nested-snp-upm
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    build-snp-qemu:
        runs-on: ubuntu-latest
        steps:
        - name: Make space
          run: |
            df -h $GITHUB_WORKSPACE
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf "$AGENT_TOOLSDIRECTORY"
            sudo rm -rf /usr/local/lib/android /opt/ghc
            df -h $GITHUB_WORKSPACE

        - name: Checkout
          uses: actions/checkout@v2
        - name: ccache
          uses: hendrikmuhs/ccache-action@v1.2
          with:
            max-size: "1G"
        - name: Build SNP qemu
          run: |
            ./run.sh
        - name: Archive artifacts
          uses: actions/upload-artifact@v2
          with:
            name: artifacts
            path: |
              snp-qemu_*.*
              source-commit.*
